environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"

version: '1.0.{build}'

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=C:\\Program Files\\Git\\mingw64\\bin;%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "call %MINICONDA%\\Scripts\\activate.bat"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels wheeler-microfluidics
  - conda update -q conda
  - conda install --yes anaconda-client conda-build jupyter path_helpers nose
  - conda info -a
  - pip install psutil
  - FOR /F "tokens=*" %%a in ('conda-build . --output') do SET PACKAGE_LOCATION=%%a
  - echo %PACKAGE_LOCATION%
  - conda-build .
  - 7z e -so %PACKAGE_LOCATION% -tbzip2 > package.tar
  - 7z x "package.tar" -opackage -ttar
  - ps: $json = Get-Content '.\\package\\info\\index.json' | Out-String | ConvertFrom-Json
  - ps: $json | Add-Member Foo 'Bar'
  - ps: ($json | ConvertTo-Json) | Out-File .\package\info\index.json
  - 7z a package2.tar .\package -ttar
  - 7z a package2.tar.bz2 package2.tar -tbzip2
  - ls
  - binstar -t %BINSTAR_TOKEN% upload --force package2.tar.bz2
build: false

test_script:
  - nosetests .\\jupyter_helpers\\tests -vv --with-xunit

after_test:
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nosetests.xml))
