image:
- Visual Studio 2015

environment:

  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"

  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\run_with_env.cmd"

version: '1.0.{build}'

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels wheeler-microfluidics
  - conda update -q conda
  - conda info -a
  - conda install --yes jupyter nose conda-build path_helpers
  - pip install coverage

build: falses

test_script:
  - "echo Running Nose Tests:"
  - nosetests
  - "echo Nose Tests Complete"

after_test:
  - "echo Tests Complete"

on_success:
  - "echo Build succesful!"

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: '*.tar.bz2'
