version: '1.0.{build}'

install:
  - set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%
  - "python --version"
  - "conda --version"
  - "echo y | conda install conda-build"
  - "conda-build .conda-recipe"
