version: '1.0.{build}'

matrix:  
  - PYTHON: "C:\\Python27_32"
    PYTHON_VERSION: "2.7"
    PYTHON_ARCH: "32"
    CONDA_PY: "27"
    CONDA_NPY: "18"

install:
  - "python --version"
  - "conda-build .conda-recipe"
