version: '1.0.{build}'

install:
  - set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%
  - "python --version"
  - "conda --version"
  - "conda config --add channels conda-forge"
  - "conda config --add channels wheeler-microfluidics"
  - "echo y | conda install jupyter"
  - "echo y | conda install nose"
  - "echo y | conda install conda-build"
  - "echo y | conda install path_helpers"
  - "echo y | conda-build .conda-recipe"
