version: '1.0.{build}'

environment:
  matrix:

    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"
      CONDA_NPY: "18"

install:
  - set PATH=C:\Anaconda2;C:\Anaconda2\Scripts;%PATH%
  - "python --version"
  - "conda --version"
  - "conda-build .conda-recipe"
