environment:

  matrix:
    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"

  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\run_with_env.cmd"

version: '1.0.{build}'

install:
  - set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%
  - "python --version"
  - "conda --version"
  - "conda config --add channels conda-forge"
  - "conda config --add channels wheeler-microfluidics"
  - "conda install --yes jupyter nose conda-build path_helpers coverage"
  - "conda-build -V"

build: false

test_script:
  - "echo Running Nose Tests:"
  - nosetests -v
  - "echo Nose Tests Complete"

after_test:
  - "echo Tests Complete"

on_success:
  - "echo Build succesful!"

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: '*.tar.bz2'
